### ISSUE TITLE
Release 1.0.0 Checklist

### ISSUE THREAD

**Issue by JasonTypesCodes** [jhipster/generator-jhipster-micronaut#189]
Release checklist for 1.0.0 :tada: 

Please add any issues, PRs, or steps that you feel should be addressed before release.

* [x] Remove "preview" messages from readme and console output
* [x] #188 (Microservice Support PR)
* [x] Remove dynamic query from options until it is supported (#171)
* [x] #166 ? (Only dev and prod profiles work) 
* [x] Update to latest JHipster 6 (#180)
* [x] Change default branch from master to main
* [x] ~Look into Gatling Support~ (later)
* [ ] Documentation (#164) (Can be post-1.0)
* [ ] Blog Post (Can be post-1.0)
* [x] Repository should only use 'save' method (#175)
* [x] Test compilation failure with entity generated with service option (#197)
* [x] Test compilation failure with required relationship (#198)
* [x] Improve integration tests by including more entities configurations (#199)

Thoughts @atomfrede @mraible @agilob @murdos ?

**Comment by agilob** [comment]
Native image with metrics is still dependent on some changes in micronaut. I could resume working on it now as the gradle plugin is in, but compilation with native image will still fail with default dependencies as micrometer isn't well supported. Issue has already been addressed by micronaut https://github.com/micronaut-projects/micronaut-core/issues/4155 but feedback isn't positive. Otherwise to compile mhipster user would have to manually remove dependencies for micrometer and remove related configuration and configuration files.

> Update to latest JHipster 6 (#180)

Would it be worth to wait for jhipster 7?

**Comment by atomfrede** [comment]
My thoughts:

* let's have a first and most likely final release based on jhipster 6
* let's get #188 merged (not sure how much work is still left)
* remove the dynamic filtering for now
* #166 is still an issue. but we could "fix" it with better documentation or e.g. by putting a file and write the default profile which is then used when starting the application
* #174 would be very cool to have, not sure if we can make it happen without other third party libraries fixing graal support
* I think it would be nice to have some dedicated documentation about this blueprint (https://github.com/jhipster/generator-jhipster-micronaut/issues/164), such that we can document e.g. different build commands and other things
* have a nice blog post ready for the release
* change the default branch from master to main
* check if we can get gatling to work or whats wrong (not required, but nice to have, e.g. for comparing boot vs micronaut performance with jhipster)

If we have a 1.0.0 release we should prepare the switch to jhipster 7 and see what will break. I would like to start with checking gatling support (if we don't have it for 1.0.0 already) and add reactive support.

@JasonTypesCodes We (the jhipster association via @avdev4j) are planning a virtual jhipster meetup. In november the topic should be jhipster and companies, maybe you (oci)/we can do a small session to celebrate the 1.0.0 release

**Comment by JasonTypesCodes** [comment]
@atomfrede I think that sounds great.  I modified the checklist above to match.  Please feel free to edit as you see fit.

> @JasonTypesCodes We (the jhipster association via @avdev4j) are planning a virtual jhipster meetup. In november the topic should be jhipster and companies, maybe you (oci)/we can do a small session to celebrate the 1.0.0 release

I think that is a great idea!

**Comment by JasonTypesCodes** [comment]
@atomfrede I created a main branch and pushed it up, but I don't seem to have rights to the repo to swap the default branch to it.  Is that something you are able to do?

**Comment by atomfrede** [comment]
😁 I don't have the permission either. I thought you have

**Comment by avdev4j** [comment]
> @atomfrede I think that sounds great. I modified the checklist above to match. Please feel free to edit as you see fit.
> 
> > @JasonTypesCodes We (the jhipster association via @avdev4j) are planning a virtual jhipster meetup. In november the topic should be jhipster and companies, maybe you (oci)/we can do a small session to celebrate the 1.0.0 release
> 
> I think that is a great idea!

Jason, If you are still interested by that please contact me on Twitter (@avdev4j) . I would love to have more companies to participate to this November virtual meetups.

**Comment by murdos** [comment]
Here are tickets I think we should fix before moving to 1.0 (in addition to the one already mentioned):
- #175
- #197
- #198
- #199

**Comment by mraible** [comment]
Adding a bug bounty so y'all can have some beers on us when this is released! 🍻

**Comment by JasonTypesCodes** [comment]
@atomfrede I have a draft PR to address a few issues I discovered while adding more entity relationships to the CI.  There is currently an issue with User entities in the integration tests that I haven't had time to figure out yet.  I'll see if I can put some time towards that today or tomorrow.  Are there any "must haves" from your point of view before 1.0.0?  From my perspective, the other items on this list can be done after 1.0.0

**Comment by atomfrede** [comment]
Sorry for the delay. I would also say let's move forward to 1.0.0. I won't make it to look into detail with gatling. The documentation is currently under discussion on the mailing list where to put it. Current state is official blueprints will be put to top level such that each blueprint has an own page (and subpages). Can I support you somehow in fixing the remaining issues in https://github.com/jhipster/generator-jhipster-micronaut/pull/213?

I will test the profile issue (#166) but it should be fixed and should we fix #175  for the 1.0.0 release?

**Comment by JasonTypesCodes** [comment]
@atomfrede I'll take a look at #175

**Comment by JasonTypesCodes** [comment]
https://github.com/jhipster/generator-jhipster-micronaut/releases/tag/v1.0.0

1.0.0 has been Released!

Thank you everyone for all of your contributions!  Especially:

@atomfrede @agilob @murdos @sendilkumarn @willbuck @ZacharyKlein  and @mraible 

----

@atomfrede and myself are working on a joint blog post and a webinar.  I think #164 will be a natural next step.

Next steps are to move towards JHipster 7 :)

Thank you again!

**Comment by atomfrede** [comment]
Thanks to everyone involved making this collaboration possible and really fun to work!

**Comment by atomfrede** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/38249

**Comment by atomfrede** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/38249
