### ISSUE TITLE
Publish Preview Release to NPM

### ISSUE THREAD

**Issue by JasonTypesCodes** [jhipster/generator-jhipster-micronaut#62]
* [x] Add appropriate "Preview" wording to documentation
* [x] Get publish rights to `generator-jhipster-micronaut`
* [x] Update to JHipster 6.8 (#53)
* [x] Update to JHipster 6.9 (#64)
* [x] Clean up Java dependencies (#23)
* [x] Update generated README (#41)

**Comment by JasonTypesCodes** [comment]
I've started on the update to 6.8.  There were some changes in webpack that I need to clean up but I don't think it will take me much more effort.  The email stuff can wait but I'd really like to get it in.

**Comment by JasonTypesCodes** [comment]
@sendilkumarn Would you be willing to grant me publish rights to https://www.npmjs.com/package/generator-jhipster-micronaut ?

**Comment by sendilkumarn** [comment]
cool let me give it

**Comment by sendilkumarn** [comment]
Sent u access, let me know if it works.
